### ISSUE TITLE
Crashes under microscope while viewing decompose recipe.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [AdlyTempleton/MineChem#135]
Whenever I put in Copper Block, Lead Block, Invar Block, any metal block except vanilla gold / iron block, the game crashes with this: http://paste.ee/p/tBMRG

Empty map decomposing crashes witht his: http://paste.ee/p/orvAx

Thermal Expansion's Energy Cells decompose in Microscope crashes witht his: http://paste.ee/p/tBMRG

In fact any items that you view in NEI that has a ridiculous amount of elements and molecules, like way, way out of the screen, it's a guaranteed crash if you put it into the microscope and check the decompose recipe.

**Comment by taljaards** [comment]
TE ducts also do the same: http://paste.ee/p/jZOEW

**Comment by MrCantaloupe** [comment]
I can confirm that this bug is still present in 5.0.4, at least with certain varieties of copper.  Possibly more items as well.  (Playing with ATLauncher's ChaosVille modpack.)

Tinker's Construct and Forestry copper ingots cause the game to lag up horribly or crash with an IndexOutOfBounds exception when attempting to look at chemical decomposition in the microscope GUI.  So do Thermal Expansion copper blocks.

UPDATE: This problem appears to affect the Decomposer as well, to some extent.  Dropping a Tinker's Construct copper ingot into the Decomposer causes the game to start lagging and the server console to spit out a warning about being unable to keep up.  However, when this happens, you can actually pull the ingot out of the Decomposer but this is impossible with the Microscope.  The Decomposer fails to decompose the ingot in the span of ten or so seconds of real-time.  Interestingly, dropping a Thermal Expansion copper block in the decomposer causes the same lag for a few seconds before spitting out a surprisingly large number (greater than 12) of stacks of Cu vials.  Should this be opened as a separate issue?

**Comment by jakimfett** [comment]
I did a bit of testing with the latest dev build, and I can't seem to duplicate the issue.

![](http://pics.jakimfett.com/14-4-22_21:21:58.png)

Loading copper ingots into the decomposer didn't produce a crash either.
![](http://pics.jakimfett.com/14-4-22_21:24:21.png)

If you could test the latest build (either from [CurseForge](http://minecraft.curseforge.com/mc-mods/minechem-5/files/) or the [Github releases page](https://github.com/jakimfett/MineChem/releases)) and let me know if this is still an issue, and if it is, I'll re-open it.
