### ISSUE TITLE
Tungsten Problem - Solution!

### ISSUE THREAD

**Issue by GMantheKing2** [AdlyTempleton/MineChem#146]
After laborious decomposing of blocks and items, I found tungsten in Netherack. The problem being that Netherack decomposes into many things and the NEI recipes will only show the first.

**Comment by jakimfett** [comment]
If I'm understanding correctly, you're having trouble finding specific elements because NEI doesn't show you how to get a specific element, only what a block might decompose into. 

Because I'm planning to redo the decomposer mechanics next (after fixing all the bugs), I'm not planning to fix this for the 5.0.5 builds.
