### ISSUE TITLE
Can no longer extract from synthesizer

### ISSUE THREAD

**Issue by Belgabor** [AdlyTempleton/MineChem#202]
After updating to 5.0.5RC1 I apparently can no longer extract items from the synthesizer with automation. Tried both Ender IO item conduits and Steve's Factory Manager, neither works.
Works fine for the decomposer though.

**Comment by jakimfett** [comment]
This was an intentional removal due to a fairly significant dupe glitch with the Synthesizer and automation. I've added a config option (disabled by default) that allows players to re-enable for SSP and server owners to re-enable at their own risk.

If you'd like to get it, [grab build #72 from Jenkins](http://jenkins.jakimfett.com/build/job/Minechem/72/)
