### ISSUE TITLE
Stuck at Loading

### ISSUE THREAD

**Issue by RothX** [AdlyTempleton/MineChem#203]
When I install Minechem, the Mojang screen gets stuck for a while. I know it's not just taking a long time, because I looked at the log, and it wasn't doing anything at all for about 5 minutes.

**Comment by jakimfett** [comment]
Please provide more information. What version of minechem are you running? What other mods are you running? 64 or 32 bit java? Can you put your logfiles on pastebin, and provide a link so I can try to troubleshoot this?

**Comment by RothX** [comment]
It won't let me put the go on paste bin because it is too long, but from looking at the log, nothing unusual seems to be happening, it just stops doing stuff. I am using Minechem 4.3.1-44. As for other mods: a lot. I don't know what Java I am using, how do I check?

**Comment by jakimfett** [comment]
That version of Minechem is extremely old...the latest version is Minechem 5.0.5-RC1. Please download the latest version for 1.6.4 and let me know if that solves your problem.

**Comment by RothX** [comment]
Sorry, I didn't realize there was a new website. I was downloading it from here: http://pixlepixmods.wordpress.com/about/
On the new site it says that particle physics was merged into Minechem, so should I uninstall it?
I updated, but it still didn't fix anything. Exact same problem.

**Comment by jakimfett** [comment]
Does Minecraft load if you remove Minechem?

Also, Particle Physics was un-merged from Minechem. Take a look at the [post I made on this topic](http://jakimfett.com/status-report/splitting-minechem/)

**Comment by RothX** [comment]
Yep. It loads perfectly. And for the record, particle physics loads fine too.

**Comment by jakimfett** [comment]
My best guess at the moment is that there's an item ID conflict. There was one other person who had an issue with this (see #177 for info on the exact problem). 

Can you pastebin the last 100ish lines of your logfile?

**Comment by RothX** [comment]
Here is the last part of the log: http://pastebin.com/wX115Qpu

I've never had an ID conflict do this before. I've seen three things happen with ID conflicts.
1. I get a message that a list of ID conflicts has been written to ID Conflicts.txt. (This is the easiest one to fix, since I can easily see every conflict and what IDs are available.)
2. It just straight up crashes. (Annoying to fix because I can only see one conflict at a time, and it doesn't tell me what is available.)
3. The game loads up, but only one of the items that is conflicting is accessible in-game, and if I try to get the other one (whether through crafting of mining or whatever) it gives me the wrong item. (Very annoying to fix because it can last a while without me noticing, and  if I'm to super familiar with the mod, or I was just mining without paying attention, I might not know what item I was even supposed to get.)

But it has never gotten stuck at loading.

**Comment by jakimfett** [comment]
Yeah, those are the most common ways for Minecraft to respond to ID conflicts, but as noted in the other issue I linked to, other people have had a problem with Minechem just causing a freeze. I probably need to intentionally cause the problem and then beat the ID mechanics until they behave.

Based on the log file, could you try (temporarily) removing Galacticraft and then Advanced Genetics? It's probably not one of them, as logfiles have a tendency to print out info after something happens (eg, it's not GC, it's whatever loads after GC), but it's worth a shot.

Just to reiterate...given that the only other person who reported the exact same symptoms had ID conflicts, and that I've personally experienced this exact same thing after Maxwolf reworked some of the item/block ID mechanics, my best guess is an ID conflict.

That said, providing more info about when the issue started popping up might be nice. Was Minechem working fine in the past, or are you just now trying to install it? If it worked fine in the past, when did that change? If It changed, what got added/removed/updated just before it stopped working?

**Comment by RothX** [comment]
I checked all my Ids being used, and the ones Minechem are using are not conflicting. However, without Minechem installed I tried putting in those IDs for another (randomly picked) mod I have. In this case Xeno's Reliquary. So basically I went into XR's config and changed the IDs to what Minechem normally uses (without Minechem installed) and it did crash, and as far as I can tell, it isn't a conflict. Here is the crash log: http://pastebin.com/5zZtL9J7
(Keep in mind this is without Minechem installed, this is just an example)

**Comment by jakimfett** [comment]
Thanks for the info. I've made a tweak to where Minechem starts assigning IDs. If you could grab [Minechem build #76 from Jenkins](http://jenkins.jakimfett.com/build/job/Minechem/76/) and let me know if deleting your existing config file fixes the problem, I'd appreciate it.

I'm not 100% sure that this will fix it. If it doesn't, try using [my config file, which I know works](http://pastebin.com/78NYcGbs).

**Comment by Maxwolf** [comment]
Sounds like a standard ID confict to me, or his configuration file is out of date and needs to be regenerated.

**Comment by RothX** [comment]
First of all, Maxwolf, I already went over this. I can't figure out how to say this without being rude, but did you actually read over all my posts? Second, Jakimfett, the new build did fix the problem after I deleted my old config. There were ID conflicts (It's unavoidable with the amount of mods I have) but it just gave the screen where it says that they have been written to IDConflicts.txt. I'm curious to know: What exactly was the problem? You can be a tiny bit technical, because I've dabbled in Minecraft's code, and I'm experienced in Java in general.

**Comment by Maxwolf** [comment]
It's OK you are not being rude.

Regardless of feelings or the number of mods you have it is still just an ID conflict. Of course I read all the posts before commenting. The configuration system and ID resolver @jakimfett is using is all coded by me anyway.

Normally a user would use something like NEI to dump ID's before adding the mod and find a nice place where it can live and consume ID's for both blocks and items. This is purely a user thing and is dependent on the number of mods installed and how they are coded.

As for your error that is you assigning a block ID above what Minecraft allows for it. Normally block ID's are limited to below the 4096 range and your assignment of 4737 triggers the: java.lang.ArrayIndexOutOfBoundsException: 4737

Just FYI and nerd knowledge the number is normally limited to 256 in the vanilla client but Forge extends this and makes it larger but you are still limited by the size of that array at 4096 (with index starting at 0 and zero being air).

That is why I say it is a configuration issue because it is. I was wrong in assuming that it needs to be regenerated, it actually just needs to be configured correctly in the first place.

**Comment by RothX** [comment]
Oh, ok. I thought I had IDs that were higher than that. I guess it was just a bug that Minechem was using the wrong IDs by default. Wouldn't that bug have happened no matter what? I'd be surprised if more people weren't having the issue. Obviously build 76 fixed the bug so I guess this is resolved.

**Comment by jakimfett** [comment]
Awesome. I'll push an RC2 right now with the fixes for this, with an advisory for people to upgrade.

Basically, the problem was that the block ID assignment code was starting above 4k, and didn't have a limit check...eg, it'd just keep incrementing until it found a free ID, regardless of whether or not it was above the 4096 limit for Minecraft block IDs. The temporary fix I added is simply to start at 256. And, obviously, this will go away when I get around to updating to 1.7

Thanks for working with me on this!
