### ISSUE TITLE
Not accepting any form of power!

### ISSUE THREAD

**Issue by storm37000** [AdlyTempleton/MineChem#204]
I have Buildcraft 4.2.2 and thermal expansion 3.0.0.7 but it still didn't work on 3.0.0.2.
It wont even connect to any buildcraft or redstone flux conduits from any of the mods and wont accept power from any engines/dynamos drectly next to it or with a pipe/conduit right next to it.  i am using version 5.0.5RC1.

**Comment by jakimfett** [comment]
I can't be 100% certain, but I think it's because you don't have the UE Core installed. I thought I had put that in the Readme, but I just checked and it's not there. I'll update that tonight, thanks for bringing this to my attention.

I know the info is on the [Minechem page on my website though](http://jakimfett.com/minecraft/minechem).

Sidenote: please don't open multiple issues for the same problem. Thanks!

**Comment by storm37000** [comment]
sorry, i though this was the website as it had changed so often http://www.minechemmod.com/index.php/download

**Comment by jakimfett** [comment]
Yeah, i'm still working on getting everything switched over to the new locations for everything. For now, just download the mod file from Curseforge. I linked the UE Core download in the readme file.

**Comment by jakimfett** [comment]
@storm37000 did adding the UE Core fix your power problem? If so, I'll go ahead and close this ticket.

**Comment by jakimfett** [comment]
Closing ticket due to lack of response. If you're still having this problem, please open a new ticket and follow the "[Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting)" on the wiki.

**Comment by MFernflower** [comment]
I added a warning to  the log file.  If anymore of these come in. Close
them right away!
