### ISSUE TITLE
Cant Pull out of Synthesizer/ Router Dupes

### ISSUE THREAD

**Issue by DGASerious** [AdlyTempleton/MineChem#207]
Hi, i was looking for a way to automatically pull items out of the synthesizer, nothing  worked until i tried using a router from the Factorization mod, which lead to me being able to pull out the synthesized item when the needed resources are present, however they werent used, therefore im stuck at either being able to pull out an unlimited amount of items or none. Will I be able to pull out of the synthesizer similar to an auto crafting table in the future? Keep up the good work.
regards Martin

**Comment by jakimfett** [comment]
@DGASerious, this is disabled by default in the latest Minechem release (5.0.5-RC1) because of the dupe glitch. If you'd like to use automation in a non-dupe way, [download the latest release from CurseForge](http://minecraft.curseforge.com/mc-mods/73373-minechem-5/files) and set "AllowAutomation" in the config file to "true".

You should then be able to use Thermal Expansion itemducts without causing dupes. I didn't test it extensively, because the decomposer is changing significantly in 5.1.x, and the automation logic will be changing.

Let me know if this "fixes" it for you.

**Comment by jakimfett** [comment]
Given the lack of response from @DGASerious, I'm closing this issue.
