### ISSUE TITLE
Chemical Synthesis Machine wont cooperate with golems, pipes etc. 

### ISSUE THREAD

**Issue by Fantasmagoria** [AdlyTempleton/MineChem#218]
Like in the title chemical synthesis machine wont cooperate with golems, pipes that pull out items. For example I wanna do carbon dioxide i put in recipe carbon and 2 oxygens, to inventory i put carbon and oxygen and i want to pull carbon dioxide but it dont works.

**Comment by jakimfett** [comment]
Thanks for reporting this. If you could please provide the information specified in the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting), I'd greatly appreciate it.

On the off chance that you're using Minechem 5.0.5-RC1, this was resolved a while back. There's a configuration option to turn this on, which is disabled by default due to a dupe glitch. If you'd like more info, you can see the discussion of this issue in the [commit comment thread](https://github.com/jakimfett/MineChem/commit/08c295001fb9de76134a92cc35e43c993b387637).

**Comment by Fantasmagoria** [comment]
I am using 5.0.5-RC1. Sorry for my question but how to turn on extracting from synthesis machine cause i dont see anything proper in config file.

**Comment by Fantasmagoria** [comment]
Never mind you can close this topic.

**Comment by jakimfett** [comment]
Thanks, let me know if you run into any problems.
