### ISSUE TITLE
Dupe Bug with Chemical Synthesis Machine and Factorization Routers

### ISSUE THREAD

**Issue by Versalkul** [AdlyTempleton/MineChem#223]
When you use a Router From Factorization to pull the synthesis results out (Extract from Slot 0), you get unlimited of the Result.

**Comment by jakimfett** [comment]
Thanks for reporting this. If you could please provide the information specified in the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting), I'd greatly appreciate it.

On the off chance that you're using Minechem 5.0.5-RC1, this was resolved a while back. There's a configuration option that disables machine automation, and is set to be disabled by default due to dupe glitches like this one. If you'd like more info, you can see the discussion of this issue in the [commit comment thread](https://github.com/jakimfett/MineChem/commit/08c295001fb9de76134a92cc35e43c993b387637).

**Comment by Versalkul** [comment]
I AM using the Version 5.0.5-RC1
Im sorry but i use a modpack (Yogscast) because i failed at getting Energy into the synthesismachine with just Factorization, Minechem, Thermal Expansion :( (But it have the newest Version of Minechem in it)
The Bug can be reproduced:
Just Put a Factorization Router on Top of A Synthesis Machine and Set it to Extract from Slot 0
Here A Vid of the Bug (My Recording Programm made Minecraft to just Render ONE chunk idk why ):
https://www.youtube.com/watch?v=pUz9PdRcMlc

P.s. I found this bug because i wasnt able to pull the item with Itemducts out of the Synthesis Machine so i think the automation is disabled

**Comment by jakimfett** [comment]
Please check your config file and tell me what the value of "B:AllowAutomation=" is.

**Comment by Versalkul** [comment]
There is No Value like this in the Config file ...
Shall i Post the Config here ?

**Comment by jakimfett** [comment]
If that value isn't in the config, then you aren't using Minechem v5.0.5-RC1. That value gets written to the config file as a default when you run minecraft if it doesn't already exist in the file.

Go ahead and pastebin your config, and post the link here. I'd also like to take a look at your log files, if you don't mind.

**Comment by Versalkul** [comment]
I Uploaded the Log (Which is Big Because i im using a Modpack), The config and the Minechem Version im using on Dropbox :
https://dl.dropboxusercontent.com/u/50817150/Minechem.zip

**Comment by jakimfett** [comment]
Is this from the Yogscast Complete pack?

**Comment by Versalkul** [comment]
Yes

**Comment by jakimfett** [comment]
Closing this issue to clean up the issue tracker. See https://github.com/jakimfett/MineChem/issues/67 for the enhancement request related to this.
