### ISSUE TITLE
Chemical Synthesis Machine no output

### ISSUE THREAD

**Issue by smaxx1337** [AdlyTempleton/MineChem#236]
Hi there, 
I have the version 5.0.5 RC2 Minechem and if I want in the Chemical Synthesis Machine craft something and take it out, it is not. I can not take it out. 

PS: I love your Mod.

EDIT: Removed pasted config

**Comment by jakimfett** [comment]
First off, I'd highly suggest re-creating your config. Rename the file, run minecraft, and then put the values (not the extra lines) from the old config to the new config. A lot of those options aren't even part of the mod anymore.

Second, could you please go through the steps in the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting)? I know that chemical synthesis works in Minechem 5.0.5-RC2, so something else is going on here. Perhaps a different mod is conflicting? Are you completely sure you're running v5.0.5-RC2? Are you running a modpack?

**Comment by smaxx1337** [comment]
Yes, i am running a modpack, not FTB or Tekkit or something else, I have created a private modpack.
Here a screenshot of my mods.
http://www.directupload.net/file/d/3720/4jjmjhnh_png.htm
And here a screenshot of the crafting:
http://www.directupload.net/file/d/3720/46p2bytl_png.htm
(i can't use it / put it out)
Aaaaand a screenshot of my !new! config.
http://www.directupload.net/file/d/3720/y8fp8r2j_png.htm

**Comment by jakimfett** [comment]
Your config looks **much** better (no more vestiges!), thanks! Did you try Minechem all by itself like the [Bug Reporting Guidelines](https://github.com/jakimfett/MineChem/wiki/Bug-Reporting) instructs you to? Really need you to follow the guidelines, please.

**Comment by molekylspektroskopi** [comment]
I second this, running YogscastCompletePack 2931RRYOGS with MineChem 5.0.5-RC2 that is included i cannot output from Chemical Synthesis Machine. As they have a giant modpack i assume something might be off. But this is with a fresh install of Yogscast Complete Modpack

As the config is generic do i need to bother you devs with or is this something the Yogscast Team needs to bother with?

**Comment by jakimfett** [comment]
Thanks for the confirmation, I'll take a look at the yogscast pack to see if I can figure out what's wrong.

As for your question about "who do I report this to", that's a bit of a sticky question. In general, it's good to follow up with the modpack developers unless the bug you're reporting is already a "known problem" with the mod. That said, mod authors like to know what's going on. Normally, I'll test the mod, and if the mod by itself has the problem, report it to the author, and if it's just the modpack that has the problem, report it to the modpack authors.

**Comment by jakimfett** [comment]
@molekylspektroskopi and @Andr0meda56 this is probably a stupid question, but does SHIFT+CLICK work?

**Comment by molekylspektroskopi** [comment]
Not sure what the Shift+Click should do.

But i have solved this issue here, the config for minechem in yogscast had B:AllowAutomation=false.
After some reading on the great Interwebz i kinda stumbled on some discussion about that and i looked it up myself in the config folder. And yes, it was false here.

Setting it to true and restarting the server made my automation work perfectly!

But i also tried to use a router to see if i could extract the item from the Synthesizer and i can create items from nothin.

It is exactly as the issue #223 that i found before here.

Using latest Minechem with latest Yogscast.

Need anything from me?

**Comment by jakimfett** [comment]
...oh. You mean this whole time, it's been about AUTOMATION?

Probably would have been best to state that at the beginning. Yes, I've disabled automation, yes, it's intentional, because there's a dupe bug that I haven't had the time to squash yet. So, either live with no automation (for now...still going to try and fix this...) or accept that dupes can and will happen.

**Comment by molekylspektroskopi** [comment]
But, i cannot pull out items from the unit without the Automation active.
But i can pull items with the router when autoamtion is set to false. Might be due to the router just forcing a pull.

But with automation and just normal active pipes i have no dupes, so that works for me =)

**Comment by jakimfett** [comment]
All that means is that the router is not respecting the automation status of the container. Not something I can fix.
