### ISSUE TITLE
Unable to scroll chemist's journal

### ISSUE THREAD

**Issue by Nostras** [AdlyTempleton/MineChem#40]
Not sure if this is intended, but once I get the page filled I'm not able to scroll down.

**Comment by MFernflower** [comment]
A video showing the glitch would be really nice. The gui code is a bit messy tough.

**Comment by Nostras** [comment]
Fill it with recipes in the microscope and once the next recipes are added to the book but not shown on the page you have no way of scrolling. The scroll bar simply doesn't work. I could make one but I don't see why that would be necessary since its easily reproducible.

**Comment by Unrepentant-Atheist** [comment]
Confirmed. Scrollbar be kaput.

Fill the journal with all sort of stuff, once the scrollbar apears, it's non-functional. Can't scroll. So the stuff you "discovered" is lost in pages you can't see.

If the scrollbar presents a huge challenge, maybe an alternative would be to turn pages like in the vanilla books?

**Comment by ramdor** [comment]
aye, confirmed, still exists in version #383

**Comment by Rosethorns** [comment]
confirmed for 383

**Comment by MisterUnnamed** [comment]
The problem is that the "handleMouseInput()" method from "GuiVerticalScrollBar.java" doesn't seem to get called. I don't really know how it work in GuiScreen and its subclasses then I can't give you a good way to fix that other than put "scrollbar.handleMouseInput()" in the "handle..." method of "GuiChemistJournal.java" (and I don't think it's a good way).

And I think you must to put a minus before "scrollBar.getScrollValue()" (line 319 of "GuiChemistJournal.java" file) to make your scrolling go the right way.

**Comment by jakimfett** [comment]
As of right now, you can scroll by clicking and dragging the black scroll item. When I rework the chemist's journal, the scroll bar will be going away, so I think I'm going to call this "fixed", for now.
